name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
 
      
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify the Terraform version
      - name: Write GCP credentials to file 
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/gcp-key.json
        shell: bash

      - name: Check if GCP secret exists
        run: ls -l $HOME/gcp-key.json
        shell: bash

      # - name: Authenticate to GCP 
      #   run: gcloud auth activate-service-account --key-file=$HOME/gcp-key.json

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json
        run: terraform plan
        working-directory: terraform

  #     - name: Terraform Apply
  #       env:
  #         GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  #       run: terraform apply -auto-approve
  #       working-directory: terraform

  # build:
  #   runs-on: ubuntu-latest
  #   needs: terraform  # Ensure the terraform job completes before running Terraform
        
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
        
  #     - name: Set up Google Cloud SDK
  #       uses: google-github-actions/setup-gcloud@v2
  #       with:
  #         project_id: resume-project-436919  # Replace with your Google Cloud project ID
  #         service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  #         export_default_credentials: true
        
  #     - name: Deploy to GCS
  #       run: |
  #         gsutil -m rsync -r website gs://medhatyagi.uk  # Sync files to GCS bucket